services:
  - type: web
    name: ubas-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: "npm ci && npm run build"
    preDeployCommand: "npm run migrate:prod"
    startCommand: "npm start"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_VERSION
        value: v1
      - key: DATABASE_URL
        fromDatabase:
          name: ubasfintrust-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://ubasfintrust.com,https://www.ubasfintrust.com,https://ubasfintrust.onrender.com
      - key: SOCKET_IO_CORS_ORIGIN
        value: https://ubasfintrust.com

  - type: web
    name: ubas-frontend
    runtime: static
    plan: free
    rootDir: .
    buildCommand: "npm ci && npm run build"
    envVars:
      - key: VITE_API_URL
        value: https://api.ubasfintrust.com/api/v1
      - key: VITE_SOCKET_URL
        value: https://api.ubasfintrust.com
      - key: VITE_APP_NAME
        value: UBAS Financial Trust
      - key: VITE_NODE_ENV
        value: production

databases:
  - name: ubasfintrust-db
    plan: free



