services:
  - type: web
    name: ubas-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: "npm ci && npm run build"
    preDeployCommand: "npm run migrate:prod || npm run migrate:verify"
    startCommand: "npm start"
    healthCheckPath: "/health/liveness"
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_VERSION
        value: v1
      - key: DATABASE_URL
        fromDatabase:
          name: ubasfintrust-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://ubasfintrust.com,https://www.ubasfintrust.com,https://ubasfintrust.onrender.com,https://ubasfintrust1.onrender.com
      - key: SOCKET_IO_CORS_ORIGIN
        value: https://ubasfintrust.com,https://www.ubasfintrust.com,https://ubasfintrust.onrender.com
      - key: DEMO_MODE
        value: "true"
      # Email / Notifications
      - key: FROM_EMAIL
        value: no-reply@alerts.ubasfintrust.com
      - key: FROM_NAME
        value: UBAS Alerts
      - key: RESEND_API_KEY
        sync: false
      # Optional SMTP (Zoho) for contact fallback
      - key: SMTP_HOST
        value: smtp.zohopro.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false

  - type: web
    name: ubas-frontend
    runtime: static
    plan: free
    buildCommand: "npm ci && npm run build"
    publishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://api.ubasfintrust.com/api/v1
      - key: VITE_SOCKET_URL
        value: https://api.ubasfintrust.com
      - key: VITE_APP_NAME
        value: UBAS Financial Trust
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_MINIMUM_DEPOSIT
        value: "1"
      - key: VITE_MINIMUM_WITHDRAWAL
        value: "20"
      - key: VITE_SIMULATE_PAYMENTS
        value: "true"
      - key: VITE_HERO_IMAGES
        value: https://images.unsplash.com/photo-1560472354-b33ff0c44a43?q=80&w=1926&auto=format,https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1950&auto=format,https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1950&auto=format
      - key: VITE_HERO_ROTATION_MS
        value: "7000"
      - key: VITE_HERO_HEIGHT_VH
        value: "50"

databases:
  - name: ubasfintrust-db
    plan: free



